### ISSUE TITLE
didn't find remove_hooks() in cam_extractor

### ISSUE THREAD

**Issue by boyofabear** [frgfm/torch-cam#191]
### Bug description

I downloaded the [cam_example](https://github.com/frgfm/torch-cam/blob/main/scripts/cam_example.py) and ran it. It stopped at remove_hooks().
I checked previous [issues](https://github.com/frgfm/torch-cam/pull/158), only to find the change of name.
I ran a [jupyter demo](https://github.com/frgfm/notebooks/blob/main/torch-cam/quicktour.ipynb). It worked fine with cam, but it didn't have a remove_hooks() method as well.
![QQ截图20221109144911](https://user-images.githubusercontent.com/38518664/200759195-6c11f36b-aa49-4abc-93a2-9cb75a897d8f.png)

Was the method dropped already?

### Code snippet to reproduce the bug

cam_extractor.remove_hooks()

### Error traceback
```
Traceback (most recent call last):
  File "cam_exp.py", line 135, in <module>
    main(args)
  File "cam_exp.py", line 84, in main
    extractor.remove_hooks()
AttributeError: 'CAM' object has no attribute 'remove_hooks'
```
### Environment

torchcam                  0.3.1                         0    frgfm

**Comment by frgfm** [comment]
Hello @boyofabear :wave: 

Thanks for opening this issue!
I just checked and I cannot reproduce this locally on 0.3.2, nor on Colab (you can use the button in the documentation to open the notebook in Colab https://frgfm.github.io/torch-cam/notebooks.html)

Moreover, as you can see, the latest release does include this method: https://github.com/frgfm/torch-cam/blob/v0.3.2/torchcam/methods/core.py#L103-L107

The change was introduced in #143 and wasn't effective in v0.3.1. Thus you only need to upgrade to v0.3.2 (latest stable release) and you should be fine :)

Let me know if you encounter other problems :v:

**Comment by boyofabear** [comment]
thanks a lot, I updated and it works fine with demo!
